Algoritmo "Variáveis"
Var
// Seção de Declarações das variáveis 
Abacate, Melancia, TotalFrutasSacola : Inteiro
Inicio
//Declaração de variáveis
Abacate <- 2
Melancia <- 3
//Declarando a variável da Soma
TotalFrutasSacola <- Abacate + Melancia
Escreva(TotalFrutasSacola)

//Trocando o valor da variável Abacate
Abacate <- 5
TotalFrutasSacola <- Abacate + Melancia
Escreva(TotalFrutasSacola)
Fimalgoritmo